# -*- coding: utf-8 -*-
'''
    Author    : Huseyin BIYIK <husenbiyik at hotmail>
    Year      : 2016
    License   : GPL

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

two = {
    'aa': 'afar',
    'ab': 'abkhazian',
    'ae': 'avestan',
    'af': 'afrikaans',
    'ak': 'akan',
    'am': 'amharic',
    'an': 'aragonese',
    'ar': 'arabic',
    'as': 'assamese',
    'av': 'avaric',
    'ay': 'aymara',
    'az': 'azerbaijani',
    'ba': 'bashkir',
    'be': 'belarusian',
    'bg': 'bulgarian',
    'bh': 'bihari',
    'bi': 'bislama',
    'bm': 'bambara',
    'bn': 'bengali',
    'bo': 'tibetan',
    'br': 'breton',
    'bs': 'bosnian',
    'ca': 'catalan',
    'ce': 'chechen',
    'ch': 'chamorro',
    'co': 'corsican',
    'cr': 'cree',
    'cs': 'czech',
    'cu': 'church',
    'cv': 'chuvash',
    'cy': 'welsh',
    'da': 'danish',
    'de': 'german',
    'dv': 'divehi',
    'dz': 'dzongkha',
    'ee': 'ewe',
    'el': 'greek,',
    'en': 'english',
    'eo': 'esperanto',
    'es': 'spanish',
    'et': 'estonian',
    'eu': 'basque',
    'fa': 'persian',
    'ff': 'fulah',
    'fi': 'finnish',
    'fj': 'fijian',
    'fo': 'faroese',
    'fr': 'french',
    'fy': 'western',
    'ga': '�rish',
    'gd': 'gaelic',
    'gl': 'galician',
    'gn': 'guarani',
    'gu': 'gujarati',
    'gv': 'manx',
    'ha': 'hausa',
    'he': 'hebrew',
    'hi': 'hindi',
    'ho': 'hiri',
    'hr': 'croatian',
    'ht': 'haitian',
    'hu': 'hungarian',
    'hy': 'armenian',
    'hz': 'herero',
    'ia': '�nterlingua',
    'id': '�ndonesian',
    'ie': '�nterlingue',
    'ig': '�gbo',
    'ii': 'sichuan',
    'ik': '�nupiaq',
    'io': '�do',
    'is': '�celandic',
    'it': '�talian',
    'iu': '�nuktitut',
    'ja': 'japanese',
    'jv': 'javanese',
    'ka': 'georgian',
    'kg': 'kongo',
    'ki': 'kikuyu',
    'kj': 'kuanyama',
    'kk': 'kazakh',
    'kl': 'kalaallisut',
    'km': 'central',
    'kn': 'kannada',
    'ko': 'korean',
    'kr': 'kanuri',
    'ks': 'kashmiri',
    'ku': 'kurdish',
    'kv': 'komi',
    'kw': 'cornish',
    'ky': 'kirghiz',
    'la': 'latin',
    'lb': 'luxembourgish',
    'lg': 'ganda',
    'li': 'limburgan',
    'ln': 'lingala',
    'lo': 'lao',
    'lt': 'lithuanian',
    'lu': 'luba-katanga',
    'lv': 'latvian',
    'mg': 'malagasy',
    'mh': 'marshallese',
    'mi': 'maori',
    'mk': 'macedonian',
    'ml': 'malayalam',
    'mn': 'mongolian',
    'mr': 'marathi',
    'ms': 'malay',
    'mt': 'maltese',
    'my': 'burmese',
    'na': 'nauru',
    'nb': 'bokm�l,',
    'nd': 'ndebele,',
    'ne': 'nepali',
    'ng': 'ndonga',
    'nl': 'dutch',
    'nn': 'norwegian',
    'no': 'norwegian',
    'nr': 'ndebele,',
    'nv': 'navajo',
    'ny': 'chichewa',
    'oc': 'occitan',
    'oj': 'ojibwa',
    'om': 'oromo',
    'or': 'oriya',
    'os': 'ossetian',
    'pa': 'panjabi',
    'pi': 'pali',
    'pl': 'polish',
    'ps': 'pushto',
    'pt': 'portuguese',
    'qu': 'quechua',
    'rm': 'romansh',
    'rn': 'rundi',
    'ro': 'romanian',
    'ru': 'russian',
    'rw': 'kinyarwanda',
    'sa': 'sanskrit',
    'sc': 'sardinian',
    'sd': 'sindhi',
    'se': 'northern',
    'sg': 'sango',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'sm': 'samoan',
    'sn': 'shona',
    'so': 'somali',
    'sq': 'albanian',
    'sr': 'serbian',
    'ss': 'swati',
    'st': 'sotho,',
    'su': 'sundanese',
    'sv': 'swedish',
    'sw': 'swahili',
    'ta': 'tamil',
    'te': 'telugu',
    'tg': 'tajik',
    'th': 'thai',
    'ti': 'tigrinya',
    'tk': 'turkmen',
    'tl': 'tagalog',
    'tn': 'tswana',
    'to': 'tonga',
    'tr': 'turkish',
    'ts': 'tsonga',
    'tt': 'tatar',
    'tw': 'twi',
    'ty': 'tahitian',
    'ug': 'uighur',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'uz': 'uzbek',
    've': 'venda',
    'vi': 'vietnamese',
    'vo': 'volap�k',
    'wa': 'walloon',
    'wo': 'wolof',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'za': 'zhuang',
    'zh': 'chinese',
    'zu': 'zulu'
    }
